#!/bin/bash

# Lunch Weather Bot Complete Setup Script
# This script automates the setup of:
# 1. Configuration file (terraform.tfvars)
# 2. Deployment process
# 3. Instructions for setting up the Slack webhook secret

set -e

echo "🍽️  Lunch Weather Bot Setup"
echo "=========================="
echo ""

# Check if we're in the terraform directory
if [ ! -f "main.tf" ]; then
    echo "❌ Error: Please run this script from the terraform directory"
    exit 1
fi

# Check if AWS CLI is configured
if ! aws sts get-caller-identity &>/dev/null; then
    echo "❌ Error: AWS CLI is not configured. Please run 'aws configure' first."
    exit 1
fi

# Function to prompt for input with default value
prompt_with_default() {
    local prompt="$1"
    local default="$2"
    local result
    
    if [ -n "$default" ]; then
        read -p "$prompt [$default]: " result
        result=${result:-$default}
    else
        read -p "$prompt: " result
    fi
    
    echo "$result"
}

# Function to prompt for yes/no
prompt_yes_no() {
    local prompt="$1"
    local default="$2"
    local result
    
    while true; do
        if [ "$default" = "y" ]; then
            read -p "$prompt [Y/n]: " result
            result=${result:-y}
        else
            read -p "$prompt [y/N]: " result
            result=${result:-n}
        fi
        
        case $result in
            [Yy]* ) return 0;;
            [Nn]* ) return 1;;
            * ) echo "Please answer yes or no.";;
        esac
    done
}

# Step 1: Check if terraform.tfvars exists and configure if needed
echo "📝 Step 1: Configuring terraform.tfvars..."
if [ ! -f "terraform.tfvars" ]; then
    echo "Creating terraform.tfvars from template..."
    
    if [ ! -f "terraform.tfvars.example" ]; then
        echo "❌ Error: terraform.tfvars.example not found"
        exit 1
    fi
    
    # Copy template
    cp terraform.tfvars.example terraform.tfvars
    
    echo ""
    echo "🔧 Let's configure your weather bot:"
    echo ""
    
    # Prompt for configuration
    echo "📍 Location Settings:"
    LOCATION_NAME=$(prompt_with_default "Location name" "Munich")
    LOCATION_LAT=$(prompt_with_default "Latitude" "48.1351")
    LOCATION_LON=$(prompt_with_default "Longitude" "11.5820")
    
    echo ""
    echo "🌐 AWS Settings:"
    AWS_REGION=$(prompt_with_default "AWS region" "eu-central-1")
    
    echo ""
    echo "🏷️  Deployment Options:"
    if prompt_yes_no "Do you want to use a deployment suffix (for multiple teams/channels)?" "n"; then
        DEPLOYMENT_SUFFIX=$(prompt_with_default "Deployment suffix (e.g., team-alpha, berlin-office)" "")
        # Validate suffix format
        if [[ ! "$DEPLOYMENT_SUFFIX" =~ ^[a-z0-9-]*$ ]]; then
            echo "❌ Deployment suffix must contain only lowercase letters, numbers, and hyphens"
            exit 1
        fi
    else
        DEPLOYMENT_SUFFIX=""
    fi
    
    # Update terraform.tfvars with user inputs
    cat > terraform.tfvars <<EOF
# Lunch Weather Bot Configuration
# Generated by setup-bot.sh on $(date)

# Location settings
location_name = "$LOCATION_NAME"
location_lat  = $LOCATION_LAT
location_lon  = $LOCATION_LON

# AWS settings
aws_region = "$AWS_REGION"

# Deployment suffix (empty for single deployment)
deployment_suffix = "$DEPLOYMENT_SUFFIX"

# Optional: Advanced settings (using defaults)
environment         = "prod"
lambda_timeout      = 60
lambda_memory       = 256
log_retention_days  = 14
EOF
    
    echo ""
    echo "✅ terraform.tfvars configured successfully!"
    echo ""
else
    echo "✅ terraform.tfvars already exists"
fi

# Step 2: Initialize Terraform
echo "🔧 Step 2: Initializing Terraform..."
terraform init

# Step 3: Build the application
echo "🏗️  Step 3: Building the application..."
cd ..
if [ -f "package.json" ]; then
    npm run build
    echo "✅ Application built successfully!"
else
    echo "❌ Error: package.json not found in parent directory"
    exit 1
fi
cd terraform

# Step 4: Deploy the weather bot
echo "🚀 Step 4: Deploying the weather bot..."
terraform plan
echo ""
if prompt_yes_no "Do you want to deploy the weather bot now?" "y"; then
    terraform apply
    echo ""
    echo "🎉 Weather bot deployed successfully!"
else
    echo "⏸️  Deployment skipped. Run 'terraform apply' when ready."
fi

# Step 5: Set up Slack webhook secret
echo "🔐 Step 5: Setting up Slack webhook secret..."
echo ""
echo "IMPORTANT: You need to manually set up the Slack webhook URL in AWS Secrets Manager:"
echo ""
echo "1. Create a Slack webhook URL:"
echo "   - Go to https://api.slack.com/apps"
echo "   - Create a new app or use existing one"
echo "   - Go to 'Incoming Webhooks' and activate it"
echo "   - Click 'Add New Webhook to Workspace'"
echo "   - Choose your channel and copy the webhook URL"
echo ""
echo "2. Store the webhook URL in AWS Secrets Manager:"
echo "   - Go to AWS Console → Secrets Manager"

# Get deployment suffix and AWS region for secret name
DEPLOYMENT_SUFFIX_VAR=$(grep "deployment_suffix" terraform.tfvars | cut -d'"' -f2)
AWS_REGION=$(grep "aws_region" terraform.tfvars | cut -d'"' -f2)
if [ -n "$DEPLOYMENT_SUFFIX_VAR" ]; then
    SECRET_NAME="lunch-bot-${DEPLOYMENT_SUFFIX_VAR}/slack-webhook"
else
    SECRET_NAME="lunch-bot/slack-webhook"
fi

echo "   - Find the secret named '$SECRET_NAME'"
echo "   - Click 'Retrieve secret value' → 'Edit'"
echo "   - Set the secret value as JSON:"
echo "     {\"webhook_url\": \"https://hooks.slack.com/services/YOUR/WEBHOOK/URL\"}"
echo "   - Save the secret"
echo ""

# Offer to set up the secret via CLI
echo "Alternatively, you can set up the secret via AWS CLI:"
echo ""
read -p "Do you have your Slack webhook URL ready? [y/N]: " HAVE_WEBHOOK
if [[ "$HAVE_WEBHOOK" =~ ^[Yy]$ ]]; then
    read -p "Enter your Slack webhook URL: " WEBHOOK_URL
    if [[ "$WEBHOOK_URL" =~ ^https://hooks\.slack\.com/services/ ]]; then
        echo "Setting up the secret via AWS CLI..."
        aws secretsmanager put-secret-value \
            --secret-id "$SECRET_NAME" \
            --secret-string "{\"webhook_url\": \"$WEBHOOK_URL\"}" \
            --region "$AWS_REGION"
        echo "✅ Slack webhook secret configured successfully!"
    else
        echo "❌ Invalid webhook URL format. Please set up the secret manually via AWS Console."
    fi
else
    echo "💡 Set up the secret manually when you have your webhook URL ready."
fi

# Step 6: Verify setup
echo "✅ Step 6: Verifying setup..."
terraform plan | head -20

# Cleanup
# (No temporary files to clean up)

echo ""
echo "🎉 Success! Lunch Weather Bot is fully configured and deployed!"
echo ""
echo "📋 What was set up:"
echo "✅ Configuration file (terraform.tfvars)"
echo "✅ Application built and deployed"
echo "✅ Lambda function ready to run"
echo "✅ Secrets Manager secret created (needs webhook URL)"
echo ""
echo "🤖 Bot Details:"
FUNCTION_NAME=$(terraform output -raw weather_check_function_name 2>/dev/null || echo "lunch-weather-bot-weather-check")
LOG_GROUP=$(terraform output -raw weather_check_log_group 2>/dev/null || echo "/aws/lambda/lunch-weather-bot-weather-check")
echo "   Lambda Function: $FUNCTION_NAME"
echo "   Log Group: $LOG_GROUP"
echo "   Schedule: Weekdays at 10 AM CEST"
echo "   Secret Name: $SECRET_NAME"
echo ""
echo "🧪 Testing:"
echo "   1. Ensure the Slack webhook secret is configured"
echo "   2. Go to AWS Console → Lambda → $FUNCTION_NAME"
echo "   3. Click 'Test' button"
echo "   4. Create test event: {}"
echo "   5. Check CloudWatch logs: $LOG_GROUP"
echo ""
echo "👥 Team Setup:"
echo "   1. Commit the changes to main.tf (but NOT terraform.tfvars)"
echo "   2. Team members run: terraform init"
echo "   3. Each team member creates their own terraform.tfvars"
echo "   4. One team member sets up the Slack webhook secret"
echo ""
echo "🔧 For multiple deployments:"
echo "   Use terraform workspaces and different deployment_suffix values" 