name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    test:
        name: Code Quality & Tests
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v6
              with:
                  node-version-file: '.nvmrc'
                  cache: 'npm'

            - name: Install dependencies
              run: npm ci

            - name: Run code quality checks
              run: npm run cq

            - name: Run tests
              run: npm run test

            - name: Build
              run: npm run build
